### ISSUE TITLE
Time out and errors...

### ISSUE THREAD

**Issue by IpPsar01** [bartmachielsen/SupermarktConnector#9]
Hi,
I need some help, I an new at Python and I can't get it to work...
On a clean OS I installed python3 and did a 'pip3 install supermarktconnector'.
When I run the example I get a time out and lots of error messages...

t1.py contains just the 3 lines:
>from supermarktconnector.jumbo import JumboConnector
>connector = JumboConnector()
>connector.search_products(query='Smint', size=1, page=0)

Probably I am doing something very obvious wrong but I can not figure it out.
Thanks for any help!

> ~/ah $ python3 t1.py
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
>     response.begin()
>   File "/usr/lib/python3.7/http/client.py", line 306, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.7/socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
>     raise SocketError(str(e))
> OSError: (104, 'ECONNRESET')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
>     response.begin()
>   File "/usr/lib/python3.7/http/client.py", line 306, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.7/socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
>     raise SocketError(str(e))
> urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "t1.py", line 3, in <module>
>     connector.search_products(query='Smint', size=1, page=0)
>   File "/home/pi/.local/lib/python3.7/site-packages/supermarktconnector/jumbo.py", line 21, in search_products
>     params={"offset": page * size, "limit": size, "q": query},
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(104, 'ECONNRESET')"))
>

**Comment by IpPsar01** [comment]
It's resolved for me for now by just using the sources and not installing them.
